### ISSUE TITLE
Traces do not update when reading from 2 channels at 2mS/div

### ISSUE THREAD

**Issue by ndm736** [nLabs-nScope/nScope-releases#1]
![nscope_bug_2ms](https://cloud.githubusercontent.com/assets/1653071/12211053/232941f6-b624-11e5-8534-ff314ade6797.PNG)

The traces do not update properly when reading from two channels at the 2mS/div time setting. Works fine reading from one, three or four channels, but not with two.

**Comment by gruvin** [comment]
Confirmed same behaviour on Mac version also. (But I guess you knew that ;-) )

**Comment by pfeerick** [comment]
Can also confirm (Windows 10 x64, nScope v0.6). Works fine when reading one channel at 2mS/div, and spits out garbage and freezes when second channel is activated. only affects the 2mS/div setting - doesn't seem to affect any other time scales.

**Comment by e-moe** [comment]
Confirmed on Mac OS X El Capitan

**Comment by davidjmeyer** [comment]
Fixed in 4c0f2e62ae6ca3fa98631b4ba2897fde7c32d775
