### ISSUE TITLE
User question

### ISSUE THREAD

**Issue by indytubehead** [nLabs-nScope/nScope-releases#10]
background: I was using nscope on an analog circuit with a +/- 15v supply. I was curious about the +15v power rail so I quickly looked at it with nscope. The readout showed a problem with regulation which is what I suspected. Then I noticed that the voltage level was 1/10 of 15v or 1.5v 

question: Does nScope have some type of auto multiplier for DC voltages? the readout acted as if there was a 10x probe attached.

**Comment by davidjmeyer** [comment]
There is no multiplier on nScope's inputs. nScope was not designed to withstand voltages outside the range of -5/+5 V, and you risk damaging the hardware by applying voltage outside this range.
