### ISSUE TITLE
nScope displays phantom sine wave

### ISSUE THREAD

**Issue by josenj** [nLabs-nScope/nScope-releases#11]
- Turn on A1
- Set frequency to 10kHz. 
- Hook up a wire from A1 to Ch1.  No other wires are [connected.]
- Turn off Ch1 in the app
- Set 'Run control' to 'Continuous' (or 'Single')
- Turn on Ch2 and you will see a sine wave
- Turning on Ch3 displays a smaller wave, Ch4 displays even a smaller wave.

Running:

![nscope version](https://cloud.githubusercontent.com/assets/20838/14164674/72afd8c0-f6cf-11e5-8eaa-0531e72ed1da.png)

Example Screenshot:

![nscope phantom sine wave](https://cloud.githubusercontent.com/assets/20838/14164569/9cf3dd6c-f6ce-11e5-8c82-5a9e1ea8bf0a.png)

**Comment by davidjmeyer** [comment]
This is actually not a phantom sine wave. It's capacitive coupling between the connections on the breadboard, and is a very real phenomenon. If you were to measure the voltage on those pins with a professional oscilloscope, it would also report the presence of a sine wave. If you want the pins to be ground, then you should connect them to ground with a wire.
