### ISSUE TITLE
Vertical position of trace is not movable

### ISSUE THREAD

**Issue by stevoclarke94** [nLabs-nScope/nScope-releases#13]
Hi, One feature it could be really useful to see is the ability to change the vertical position of a trace. Say, for example, you have a signal that is min 2V and max 5V, it would be really nice to centre this on the graph so you can fill the screen with it rather than only having it in the top section? Thanks

**Comment by KoliadaES** [comment]
Actually, this should be a generic, per channel, zero offset - regardless of scaling.
This is critical for debugging i/o (SPI, UART, etc) as you don't want the signals to overlap each other.

**Comment by davidjmeyer** [comment]
Fixed in 4c0f2e62ae6ca3fa98631b4ba2897fde7c32d775
