### ISSUE TITLE
ARM build deb link dead on nscope.org

### ISSUE THREAD

**Issue by jarvisschultz** [nLabs-nScope/nScope-releases#14]
As of today, the link for the ARM deb on the [download page](http://www.nscope.org/download/) of nscope.org points to http://www.nscope.org/prerelease2015/v06/linux/nscope_0.6-1_arm.deb However, that link is not working.

I was able to download the build from https://github.com/nLabs-nScope/nScope/blob/master/linux/nScope_0.6-1_arm.deb

**Comment by davidjmeyer** [comment]
case-sensitivity error, fixed now. thanks Jarvis
