### ISSUE TITLE
windows install package corrupted signature

### ISSUE THREAD

**Issue by tripoche** [nLabs-nScope/nScope-releases#15]
cannot install windows version:
after download windows complains about a corrupted signature
"The signature of nScopeSetup.msi is corrupt or invalid"

**Comment by davidjmeyer** [comment]
We haven't signed the software, so that's probably the cause of the message. You should still be able to install the software without it signed by manually allowing it, or disabling the security setting that prevents un-signed software from running.

**Comment by tripoche** [comment]
Thanks. I was eventually able to download the package and install the software using a different browser (Firefox)
