### ISSUE TITLE
Failed to Connect

### ISSUE THREAD

**Issue by AllieSalomon** [nLabs-nScope/nScope-releases#17]
I am using a 2013 nScope and just redownloaded the software. My board is getting power and my computer recognizes the device as an nScope, but the nScope software does not recognize it and is failing to connect. Is it a back compatibility issue or is there something else I can try?

**Comment by davidjmeyer** [comment]
For the 2013 nScope, you need to use the legacy software.

http://www.nscope.org/legacy-versions/
