### ISSUE TITLE
First time using: failed to connect

### ISSUE THREAD

**Issue by stgnet** [nLabs-nScope/nScope-releases#36]
This is the first time I'm trying to use the nScope received via KS.  I've downloaded windows 0.8 app, and when I start it I get failed to connect error.  Running on Windows 10.  Pressing power button lights up red 5v and blue -5v lights.  Unsure how to resolve issue.

**Comment by davidjmeyer** [comment]
If the green lights are not showing, then nScope is not properly connecting to the computer.

Can you try a different USB cable, or try wiggling the USB cable to see if it's a connection problem?

**Comment by stgnet** [comment]
Issue was resolved by using a usb 2.0 port instead of a usb 3.0 port.

**Comment by davidjmeyer** [comment]
Interesting, thanks for following up.
