### ISSUE TITLE
Link to nScope Source Code

### ISSUE THREAD

**Issue by ted-miller** [nLabs-nScope/nScope-releases#7]
I am wondering if the source code for your nScope GUI is open source.  I am interested in making some minor modifications for my personal use.  

On the Version 0.6 "release" page, there are two links labeled as source code archives.  However, those archives just contain the msi/dmg binaries.   Can these be updated with the source code for your application?

Thank you.
![image](https://cloud.githubusercontent.com/assets/4623811/13400336/4226e2d2-ded5-11e5-884c-f5797c01f2a3.png)

**Comment by davidjmeyer** [comment]
nScope isn't open source as yet. The "source code" zips are autogenerated by github's release feature.
